### PR TITLE
Add basic stuff for comparing investments with FPI

### PR DESCRIPTION
**Pull request by iryney**
This change is [Reviewable](https://reviewable.io/reviews/baaraban/zimbaboom/6)

### CODE REVIEW

**Comment by mykhaly** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[investments_vs_fpi.py, line 4 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7HfA0uIgJ-5rq-Guz:-Kx7HfA0uIgJ-5rq-Gv-:bjp9hb2) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L4)):*
> ```Python
> import matplotlib.pyplot as plt
> 
> fpi_dataset_path = 'Food_production_index_through_years.csv'
> ```

Глобальні змінні тре називати капсом.

---

*[investments_vs_fpi.py, line 17 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7FuG7LGKjKotV9On3:-Kx7FuG7LGKjKotV9On4:bw7hcvg) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L17)):*
> ```Python
>     # filter by country from 2001 year
>     country_data = dataset[dataset["Country Name"] == country]
>     country_from_2001 = country_data[country_data.columns[-17:-3]]
> ```

Виглядає як хардкод. Можна ж якось пофільтрувати саме по роках, нє?

---

*[investments_vs_fpi.py, line 79 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7GJQ0Y3EEy2dCxPlb:-Kx7GJQ0Y3EEy2dCxPlc:b-cjl5wj) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L79)):*
> ```Python
>                          label='{} {}'.format(country, type))
>         plots.append(plot)
>     plt.legend(handles=[*plots])
> ```

Треба додати туду, щоб зробити підписи до кожного графіка.

---

*[investments_vs_fpi.py, line 106 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7HHr2FbYMdz-WE0vC:-Kx7HHr2FbYMdz-WE0vD:bnti8no) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L106)):*
> ```Python
>                          label='{} FPI'.format(country))
>     axes = plt.gca()
>     axes.set_xlim(2000, 2014)
> ```

А чо не просто 
```
plt.gca().set_xlim(2000, 2014)
```
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Comment by iryney** [comment]
*[investments_vs_fpi.py, line 79 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7GJQ0Y3EEy2dCxPlb:-Kx7J0q9yEEDyXKpi7Re:b-tzggs9) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L79)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary><blockquote>

Треба додати туду, щоб зробити підписи до кожного графіка.
</blockquote></details>

Так там і є підписи до кожного графіка

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Comment by iryney** [comment]
*[investments_vs_fpi.py, line 17 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7FuG7LGKjKotV9On3:-Kx7Ip5MvL2Pov12CWEx:b-wm2vm2) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L17)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary><blockquote>

Виглядає як хардкод. Можна ж якось пофільтрувати саме по роках, нє?
</blockquote></details>

Якось можна, але то кончений датасет. Я ще пограюсь з ним, щоб нормально то зробити 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Comment by mykhaly** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[investments_vs_fpi.py, line 79 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7GJQ0Y3EEy2dCxPlb:-Kx87iXhc6OTmIQfTdoM:b-zfmh5l) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L79)):*
<details><summary><i>Previously, iryney (Irynei Baran) wrote…</i></summary><blockquote>

Так там і є підписи до кожного графіка
</blockquote></details>

Заєбіще.

---

*[investments_vs_fpi.py, line 106 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7HHr2FbYMdz-WE0vC:-Kx87n6EXcfdBDFchyN0:b-n5ui6j) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L106)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary><blockquote>

А чо не просто 
```
plt.gca().set_xlim(2000, 2014)
```
?
</blockquote></details>

Тут теж тре ці константи мін макс років.

---

*[investments_vs_fpi.py, line 65 at r2](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx87Y-BWOmG2aHIA_o7:-Kx87Y-BWOmG2aHIA_o8:b-gzsdap) ([raw file](https://github.com/baaraban/zimbaboom/blob/76a8e571f6b108655837c537abd4b0778813f59e/investments_vs_fpi.py#L65)):*
> ```Python
>     :param normalize: whether to normalize data
>     """
>     plt.gca().set_xlim(2000, 2015)
> ```

Треба винести 2001 і 2014 як глобальні константи і тут їх заюзати як `MIN_YEAR - 1` і `MAX_YEAR + 1`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Comment by iryney** [comment]
*[investments_vs_fpi.py, line 106 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7HHr2FbYMdz-WE0vC:-Kx8D1Sp3yHfN_TD1sfU:b3lkf) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L106)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary><blockquote>

Тут теж тре ці константи мін макс років.
</blockquote></details>

є

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Comment by iryney** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[investments_vs_fpi.py, line 4 at r1](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx7HfA0uIgJ-5rq-Guz:-Kx8Cv8hIKZtLrcGEyel:b3lkf) ([raw file](https://github.com/baaraban/zimbaboom/blob/246bde57595f80a5c4abcffdfdc3b35c8a7e5820/investments_vs_fpi.py#L4)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary><blockquote>

Глобальні змінні тре називати капсом.
</blockquote></details>

є

---

*[investments_vs_fpi.py, line 65 at r2](https://reviewable.io:443/reviews/baaraban/zimbaboom/6#-Kx87Y-BWOmG2aHIA_o7:-Kx8CyfBrEeuyC3kssw_:b3lkf) ([raw file](https://github.com/baaraban/zimbaboom/blob/76a8e571f6b108655837c537abd4b0778813f59e/investments_vs_fpi.py#L65)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary><blockquote>

Треба винести 2001 і 2014 як глобальні константи і тут їх заюзати як `MIN_YEAR - 1` і `MAX_YEAR + 1`.
</blockquote></details>

є

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Comment by mykhaly** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/baaraban/zimbaboom/6)*

**Pull request merged**
